### ISSUE TITLE
Problem with dataclicklistener

### ISSUE THREAD

**Issue by renevl** [ISchwarz23/SortableTableView#100]
I need to obtain the data of the table view when I click in a checkbox but when I do it, the event doesn't execute.

this is my table adapter:
`public class cTableAdapter extends TableDataAdapter<Object[]>
{

    private Object[]data_row;

    public cTableAdapter(Context context, ArrayList<Object[]> data) {
        super(context, data);
    }

    @Override
    public View getCellView(int rowIndex, int columnIndex, ViewGroup parentView) {
       data_row=getRowData(rowIndex);
        View renderedView;
       switch (columnIndex)
       {
           case 0:
               renderedView =renderColumn0();
           break;
           default:
               renderedView = renderColumn1(columnIndex);
           break;
       }
       return renderedView;
    }
    private View renderColumn0()
    {
       CheckBox cbx_column=new CheckBox(getContext());
       cbx_column.setChecked(false);
       return cbx_column;
    }

    private View renderColumn1(int columnIndex)
    {
        TextView textView = new TextView(getContext());
        textView.setText(data_row[columnIndex].toString());
        textView.setTextColor(ContextCompat.getColor(getContext(), R.color.text_control_1));
        textView.setPadding(10,10,10,10);
        return textView;
    }
`}

And this is the dataclicklistener event.

`table_products.addDataClickListener(new TableDataClickListener<Object[]>() {
            @Override
            public void onDataClicked(int rowIndex, Object[] clickedData) {
               AVMVOR1IDN=res_array.get(4).get(rowIndex)[7].toString();
            }
  });`

**Comment by ISchwarz23** [comment]
Hi @renevl,

I guess the table row clicked is not called, because the table row was not clicked but the CheckBox itself. So listen for clicks on the CheckBox you need to add the corresponding listener to the CheckBox.

Please make sure before creating new issues, that the problem is inside the library (and not in the use of the Android API). As the library is used in more that 1700 apps each month it is very unlikely that core functionalities like showing and clicking data is not working in one dedicated case. But if there are issues with the library (and I'm sure there are some bugs hiding) feel free to report. :)

Best regards,
Ingo

**Comment by renevl** [comment]
But It is not only when I clicked the checkbox, I try to click in another part of the row and the event is not called.

**Comment by ISchwarz23** [comment]
Then the click event is maybe consumed by any other ui component.

**Comment by renevl** [comment]
So,
 how do I get the rowIndex of the item I clicked with the checbox? due to the fact the event is not called when i click the row.

**Comment by ISchwarz23** [comment]
Can you check and uncheck the CheckBox by clicking?

**Comment by renevl** [comment]
Yes

**Comment by ISchwarz23** [comment]
So add a listener to them in the adapter and pass the row index to it.

**Comment by renevl** [comment]
Thank you, I put the row index in the checkbox id to get the rowdata
