### ISSUE TITLE
Adding data to dataadapter not possible due to static ++ row color has issues

### ISSUE THREAD

**Issue by waleedmakarem** [ISchwarz23/SortableTableView#123]
Dear Sir, 
Simply, library is great. Thanks... I am new to android programming, but library looks quite simple.
I have below issue :
 1-  into one activity (Activity A) it displays the tablelayout. It has a button  to add new data. when pressed, opens new activity (activity B) to add fields of the table. how to do this ?.
 ----- I have set in ActivityA (public   NewLocTableDataAdapter  carTableDataAdapter ) , but i cannot access teh DataAdapter class from ActivityB.
------ I have added a method to ActivityB   ( Locations_new.Addminetoo("dsf","sdf","sdfsdf" );), and into ActivityA , defined a function to add these data

      public    void   Addminetoo (  String locname,String Address,String Speciality) {
         final clsLocationNew newlocation = new clsLocationNew(locname,Address,Speciality, (byte) 0, 0);
         carTableDataAdapter.getData().add(newlocation); // carTableDataAdapter is defined as pubic into this class
       // supdate();
    }

but I get this error.
      non-static method Addminetoo(String,String,String) cannot be referenced from a static context

2----- I have implemente row selection color , but seems that textcolor is not fully colored, while image cells is fully color. please refer to below screenshot :  [https://ibb.co/jmh7d6](https://ibb.co/jmh7d6)

**Comment by ISchwarz23** [comment]
Dear @waleedmakarem,

1) The issue here is not related to the tableview. It is more general about how you manage the data inside your app. As you have recognized the data is valid not only inside one Activity but most propably over the whole app. Have a look on the Android documentation about how to persist your data.

2) To set the background of rows use the `TableRowBackgroundProvider`.
