### ISSUE TITLE
ScrollView for several SortableTableViews

### ISSUE THREAD

**Issue by gabrieltm** [ISchwarz23/SortableTableView#26]
Hello, i was trying to put several tables inside a ScrollView, for example:

`<ScrollView
...
<RelativeLayout
...
<HorizontalScrollView
...
<SortableTableView
...
`

I want to create several SortableTableViews, however when i scroll vertically through the screen, the vertical scrolling inside the SortableTableViews doesn't work anymore (if it has like 50 rows of data and i'm setting the height to show only 4 at once). Do you know if this is fixable?

Thanks.

**Comment by ISchwarz23** [comment]
Hi @gabrieltm  
if I understood you correctly you have a TableView inside a ScrollView. The issue is, that the TableView contains also a ScrollView. So of the tries to scroll there are two ScrollViews "under his finger". I think the scroll gesture is passed by Android to the one which is outer most. So I don't think there is a way this can be fixed.  
Without having seen your application I would say it is to "complicated" for a mobile device. The user would be overstrained by the possibilities in one activity. So I would generally advice to simplify this to have a more clean UI and a better UX.
