### ISSUE TITLE
How to add gesture events to SortableTableView

### ISSUE THREAD

**Issue by santoshgupta901** [ISchwarz23/SortableTableView#44]
I want to add gesture event like swipe, double table ,longPress events to SorttableTableView how could I implement this feature. I try  to add onTouchEvent to this view but does not working.

**Comment by ISchwarz23** [comment]
Hi @santoshgupta901,

the **long press** could be a new cool feature, I think this will be part of the next release. But the **double tab** is something which is not "android like". I'm not convinced about it because of the following reasons:
- Long Press is a recommeded interaction in the UI Guidelines, double touch is not.
- It's what users expect; a user might not find a double touch action as they won't go looking for it
- Implementing Double Touch will affect handling of single touches, because you'll have to wait to see if every single touch turns into a double touch before you can process it.  

If you want to listen for **swipe** events you can do this using [this](http://stackoverflow.com/questions/17520750/list-view-item-swipe-left-and-swipe-right) approach.

Best regards,
Ingo

**Comment by ISchwarz23** [comment]
Hi @santoshgupta901,

I am pleased to tell you, that the "Data Long Listening" is part of the tableview version 2.2.0 which was just released some minutes ago.

Best regards,
Ingo
