### ISSUE TITLE
How to remove all rows?

### ISSUE THREAD

**Issue by EgyptianM** [ISchwarz23/SortableTableView#69]
Hi Ingo,
I want to remove all rows before refreshing the table but when I use `removeAllViews()` or any other method related to removing view it removes all the table including the header and when I set the adapter again it never shows again.

Thank you in advance

**Comment by ISchwarz23** [comment]
Hi Mohammad,

I think what you want to do is, clear the data displayed in the view, instead of removing the views themselves (as this is up to the TableView, depending on the data that shall be displayed).
The data of a TableView is managed by the `TableDataAdapter`. So what you need to do is clear the data and tell that the data has changed.
```java
tableDataAdapter.getData().clear();
tableDataAdapter.notifyDataSetChanged();
```

Best regards,
Ingo

**Comment by EgyptianM** [comment]
Yes exactly, this is what I want to do.
I just tried your solution and it's working like a charm.

Thank you very much.
